/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package systems.manifold;

//import org.gradle.api.JavaVersion;
import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.gradle.api.tasks.compile.JavaCompile;
//import org.gradle.api.plugins.JavaPluginExtension;

/**
 * A simple 'hello world' plugin.
 */
public class ManifoldGradlePlugin implements Plugin<Project> {

    public static final String MANIFOLD_EXTENSION = "manifold";

    public void apply(Project project) {
        project.getPluginManager().apply("java");
//        JavaPluginExtension java = project.getExtensions().getByType(JavaPluginExtension.class);

        // It might make sense to not apply this as part of the plugin; enterprise manifold consumers might not want this
        // project.getRepositories().mavenCentral();

        project.getExtensions().create(MANIFOLD_EXTENSION, ManifoldExtension.class);

//        java.setSourceCompatibility(JavaVersion.VERSION_11);
//        java.setTargetCompatibility(JavaVersion.VERSION_11);

        project.getTasks().withType(JavaCompile.class, javaCompile -> {
            javaCompile.getOptions().getCompilerArgs().add("-Xplugin:Manifold");
        });
    }
}
